routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware'=>'auth'],function(){
    Route::resource('typePeople','TypePeopleController');
    Route::resource('typeUser','TypeUserController');
    Route::resource('typeHomework','TypeHomeworkController');
    Route::resource('ciclo','CicloController');
    Route::resource('level','LevelController');
    Route::resource('matter','MatterController');
    Route::resource('section','SectionController');
    Route::resource('student','StudentController');
    Route::resource('teacher','TeacherController');
    Route::resource('people','PeopleController');
    Route::resource('period','PeriodController');
    Route::resource('homework','HomeworkController');
    Route::resource('number','NumberController');
    Route::resource('student_homework','StudentHomeworkController');
    Route::resource('level_section','LevelSectionController');
    Route::resource('student_level','StudentLevelController');
    Route::resource('user','UserController');
    Route::resource('student_people','StudenPeopleController');
    Route::get('descargar-notas/{id}', 'StudentController@print_nota');
    
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    protected $fillable = ['code','fullname','birthday','cui','picture_student','description'];

    public function student_peoples(){
        return $this->hasMany('App\Models\StudentPeople');
    }

    public function student_homeworks(){
        return $this->hasMany('App\Models\StudentHomework');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use App\Models\Matter;
use App\Models\Homework;
use App\Models\TypeHomework;
use App\Models\LevelSection;
use App\Models\StudentHomework;
use App\Models\StudentLevel;
use Illuminate\Http\Request;
use App\Http\Requests\StudentFormRequest;
use PDF;
use Carbon\Carbon;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $students = Student::orderBy('id','desc')->where('is_active',1)->simplePaginate(20);
        $now = Carbon::now();
        $homeworks = Homework::all();
        $level_sections = LevelSection::all();
        $student_homeworks = StudentHomework::all();
        $total_puntos = 0;
        $student_levels = StudentLevel::all();
        $matters = Matter::all();
        if(isset($students)){
            return view('student.index',compact('students','homeworks','level_sections','student_homeworks','student_levels','total_puntos','matters','now'));
        }else{
            return view('student.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    public function print_nota($id){
        $now = Carbon::now();
        $now = $now->locale('es');
        $homework = StudentHomework::where('student_id',$id)->get();
        $student_level = StudentLevel::where('student_id',$id)->get();
        $level = $student_level->first();
        $matters = Matter::all();
        $student = Student::findOrFail($id);
        $type_homeworks = TypeHomework::all();
        $pdf = PDF::loadView('pdf.notas',compact('homework','student_level','student','type_homeworks','level','matters','now'));
        $pdf->setPaper('a4','portrait');
        return $pdf->download('Notas -'.$student->fullname.'.pdf');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentFormRequest $request)
    {
        //
        Student::create($request->all());
        return redirect('student');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $student = Student::findOrFail($id);
        $student->update($request->all());
        return redirect('student');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $student = Student::findOrFail($id);
        $student->is_active = 0;
        $student->update();
        return redirect('student');
    }
}

resources/views/student/addHomework.blade.php
<div class="modal fade" id="addHomework-{{$student->id}}">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header btn btn-primary">
          <h5 class="display-6">Trabajos Calificados</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h4>Estudiante: {{$student->fullname}}</h4><hr>
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>No.</th>
                <th>Materia</th>
                <th>Catedrático</th>
              </tr>
            </thead>
            @foreach($matters as $ma)
              @foreach($student_levels as $sl)
                @if($sl->student_id == $student->id)
                  @if($sl->level_section->matter->id == $ma->id)
                    <tbody>
                      <tr>
                        <td>{{$loop->iteration}}</td>
                        <td><button type="button" data-bs-toggle="modal" data-bs-whatever="{{$ma->id}}" data-bs-target="#nota-{{$student->id}}" data-bs-dismiss="modal fade" class="btn btn-info">{{$sl->level_section->matter->name}}</button></td>
                        <td>{{$sl->level_section->teacher->fullname}}</td>
                      </tr>
                      <tr>
                        <th scope="row">No.</th>
                        <th scope="row">Trabajo</th>
                        <th scope="row">Puntos</th>
                        @php $total_puntos = 0; $total_matter = 0; @endphp
                        @foreach($student_homeworks as $sh)
                          @if($sh->student_id == $student->id)
                            @if($sh->homework->matter_id == $ma->id)
                              <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$sh->homework->name}}</td>
                                <td>{{$sh->points}}/{{$sh->homework->points}}</td>
                              </tr>
                              @php $total_puntos = $total_puntos + $sh->points @endphp
                              @php $total_matter = $total_matter + $sh->homework->points @endphp
                            @endif
                          @endif
                        @endforeach
                        <tr>
                          <td></td>
                          @if($total_puntos<59)<td style="background: red; color:white;">Rendimiento Bajo</td><td style="background: red; color:white"> 
                          @elseif($total_puntos>=60 && $total_puntos<=70)<td style="background: #fcba03; color:white;">Rendimiento Regular</td> <td style="background: #fcba03"> 
                          @elseif($total_puntos>=71 && $total_puntos<=90)<td style="background: yellow;">Rendimiento Aceptado</td> <td style="background:yellow;">
                          @elseif($total_puntos>=91 && $total_puntos<=100)<td style="background: green; color:white;">Excelente</td> <td style="background:green; color:white">
                          @endif
                          {{$total_puntos}}/{{$total_matter}}</td>
                          
                        </tr>
                        
                      </tr>
                    </tbody>
                  @endif
                @endif
              @endforeach
            @endforeach
          </table>
        </div>
      </div>
    </div>
  </div>

resources/views/student/delete.blade.php
<div class="modal fade" id="eliminarStudent-{{$student->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header btn btn-danger">
          <h5 class="modal-title">Eliminar</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{{route('student.destroy',$student->id)}}" method="post" class="form">
                <input name="_method" type="hidden" value="DELETE">
                @csrf
                <h4>Confirma que desea eliminar el Estudiante. <b>{{$student->fullname}}</b></h4>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancelar</button>
                  <button class="btn btn-danger">Eliminar</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

resources/views/student/editar.blade.php
<div class="modal fade" id="editarStudent-{{$student->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header btn btn-primary">
          <h5 class="display-6">Editar</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{{route('student.update',$student->id)}}" method="post" class="form">
                <input name="_method" type="hidden" value="PATCH">
                @csrf
                <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-sharp fa-solid fa-barcode"></i></i></span>
                  <input type="text" name="code" value="{{$student->code}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-user"></i></span>
                  <input type="text" name="fullname" value="{{$student->fullname}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-address-card"></i></span>
                  <input type="text" name="cui" onkeypress="return validar(event);" value="{{$student->cui}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-cake-candles"></i></span>
                  <input type="date" name="birthday" max="2017-01-01" value="{{$student->birthday}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-regular fa-comment"></i></span>
                <textarea name="description" class="form-control" col=10 row=2 placeholder="Comentario" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg">{{$student->description}}</textarea>
            </div>
              <div class="input-group input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-image"></i></span>
                  <img src="" alt="foto" class="form-control">
              </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                  <button class="btn btn-primary">Editar</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

resources/views/student/index.blade.php
@extends('layouts.app');
@section('content')
<div class="container">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row">
        <div class="col text-center shadow-lg p-3 mb-5 bg-body rounded">
            <h3>Nuevo Estudiante</h3>
            <hr>
            <form action="{{route('student.store')}}" method="post" class="form">
                @csrf
                <div class="input-group mb-3 input-group-lg">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-sharp fa-solid fa-barcode"></i></span>
                    <input type="text" name="code" class="form-control" placeholder="Código de Alumno" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
                </div>
                <div class="input-group mb-3 input-group-lg">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-user"></i></span>
                    <input type="text" name="fullname" class="form-control" placeholder="Nombre Completo" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
                </div>
                <div class="input-group mb-3 input-group-lg">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-address-card"></i></span>
                    <input type="text" name="cui" class="form-control" placeholder="C.U.I." onkeypress="return validar(event);" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
                </div>
                <div class="input-group mb-3 input-group-lg">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-cake-candles"></i></span>
                    <input type="date" name="birthday" max="2017-01-01" class="form-control" placeholder="Fecha de Cumpleaños" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
                </div>
                <br><br><br><br><br>
               
                <hr>
                <button type="submit" class="btn btn-success">Guardar</button>
                <button class="btn btn-danger">Cancelar</button>
            </form>
        </div>
        <div class="col-md-9 text-center shadow-lg p-3 mb-5 bg-body rounded">
            <h3>Listado de Estudiantes</h3>
            <hr>
            @if(isset($students))
                <table class="table table-striped table-hover">
                    <thead class="bg-primary text-white">
                        <tr>
                            <th scope="row">No.</th>
                            <th scope="row">Código</th>
                            <th scope="row">Nombre</th>
                            <th scope="row">Edad</th>
                            <th scope="row">C.U.I.</th>
                            <th scope="row">Acción</th>
                        </tr>
                    </thead>
                    @foreach($students as $student)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$student->code}}</td>
                        <td><a class="nav nav-link" data-bs-target="#addHomework-{{$student->id}}" data-bs-toggle="modal">{{$student->fullname}}</a></td>
                        <td>{{\Carbon\Carbon::parse($student->birthday)->age}} años.</td>
                        <td>{{$student->cui}}</td>
                        <td>
                            <a href="" data-bs-toggle="modal" data-bs-target="#editarStudent-{{$student->id}}"><i data-fa-symbol="edit" class="fa-solid fa-pencil fa-fw"></i></a>
                            @if(Auth::user()->type_user->name == 'administrador')
                            <a href="" data-bs-toggle="modal" data-bs-target="#eliminarStudent-{{$student->id}}"><i data-fa-symbol="delete" class="fa-solid fa-trash fa-fw" style="color:red"></i></a>
                            @endif
                            <a href="{{action('StudentController@print_nota',$student->id)}}" ><i data-fa-symbol="delete" class="fa-solid fa-print fa-fw" style="color:green"></i></a>
                        </td>
                        <td>
                            @include('student.addHomework')
                        </td>
                    </tr>
                    
                    
                        @include('student.editar')
                        @include('student.delete')
                        @endforeach
                    </table>
                {{ $students->links() }}
            @else
                <h3>No Existen Registros!</h3>
                <h5><--- Agrega uno </h5>
            @endif
        </div>
    </div>
</div>

@endsection

resources/views/student/notas.blade.php
<div class="modal" id="nota-{{$student->id}}">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header btn btn-primary">
          <h5 class="display-6">Trabajos Realizados</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <table class="table table-striped table-hover">
                <thead class="bg-primary text-white">
                    <tr>
                        <th scope="row">No.</th>
                        <th scope="row">Alumno</th>
                        <th scope="row">Trabajo</th>
                        <th scope="row">Puntos</th>
                    </tr>
                </thead>
                @foreach($student_homeworks as $sh)
                    @foreach($matters as $matter)
                        @if($sh->student_id == $student->id)
                            @if($sh->homework->matter_id)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$sh->student->fullname}}</td>
                                    <td>{{$sh->homework->name}}</td>
                                    <td>{{$sh->points}}/{{$sh->homework->points}}</td>
                                </tr>
                            @endif
                        @endif
                    @endforeach
                @endforeach
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>{{$total_puntos}}/100</td>
                </tr>
            </table>
        </div>
      </div>
    </div>
  </div>