routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware'=>'auth'],function(){
    Route::resource('typePeople','TypePeopleController');
    Route::resource('typeUser','TypeUserController');
    Route::resource('typeHomework','TypeHomeworkController');
    Route::resource('ciclo','CicloController');
    Route::resource('level','LevelController');
    Route::resource('matter','MatterController');
    Route::resource('section','SectionController');
    Route::resource('student','StudentController');
    Route::resource('teacher','TeacherController');
    Route::resource('people','PeopleController');
    Route::resource('period','PeriodController');
    Route::resource('homework','HomeworkController');
    Route::resource('number','NumberController');
    Route::resource('student_homework','StudentHomeworkController');
    Route::resource('level_section','LevelSectionController');
    Route::resource('student_level','StudentLevelController');
    Route::resource('user','UserController');
    Route::resource('student_people','StudenPeopleController');
    Route::get('descargar-notas/{id}', 'StudentController@print_nota');
    
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/StudentHomework.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class StudentHomework extends Model
{
    use HasFactory;

    protected $fillable = ['student_id','homework_id','points','level_section_id'];

    public function student(){
        return $this->belongsTo('App\Models\Student');
    }
    public function homework(){
        return $this->belongsTo('App\Models\Homework');
    }
    public function level_section(){
        return $this->belongsTo('App\Models\LevelSection');
    }
}

app/Http/Controllers/StudentHomeworkController.php
<?php

namespace App\Http\Controllers;

use App\Models\StudentHomework;
use App\Models\Homework;
use App\Models\LevelSection;
use App\Models\Student;
use Illuminate\Http\Request;

class StudentHomeworkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $homeworks = Homework::all();
        $level_sections = LevelSection::all();
        $student_homeworks = StudentHomework::orderBy('id','desc')->simplePaginate(7);
        $sh = StudentHomework::all();
        $total_puntos = $sh->sum('points');
        $students = Student::all();
        if(isset($student_homeworks)){
            return view('student_homework.index',compact('student_homeworks','homeworks','level_sections','total_puntos','students'));
        }else{
            return view('student_homework.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        StudentHomework::create($request->all());
        return redirect('student');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\StudentHomework  $studentHomework
     * @return \Illuminate\Http\Response
     */
    public function show(StudentHomework $studentHomework)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\StudentHomework  $studentHomework
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\StudentHomework  $studentHomework
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $sh = StudentHomework::findOrFail($id);
        $sh->update($request->all());
        return redirect('student_homework');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\StudentHomework  $studentHomework
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $sh = StudentHomework::findOrFail($id);
        $sh->delete();
        return redirect('student_homework');
    }
}

resources/views/student_homework/delete.blade.php
<div class="modal fade" id="eliminarTeacher-{{$teacher->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header btn btn-danger">
          <h5 class="modal-title">Eliminar</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{{route('teacher.destroy',$teacher->id)}}" method="post" class="form">
                <input name="_method" type="hidden" value="DELETE">
                @csrf
                <h4>Confirma que desea eliminar el Catedrático. <b>{{$teacher->fullname}}</b></h4>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancelar</button>
                  <button class="btn btn-danger">Eliminar</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

resources/views/student_homework/editar.blade.php
<div class="modal fade" id="editarTeacher-{{$teacher->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header btn btn-primary">
          <h5 class="display-6">Editar</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{{route('teacher.update',$teacher->id)}}" method="post" class="form">
                <input name="_method" type="hidden" value="PATCH">
                @csrf
                <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-sharp fa-solid fa-barcode"></i></i></span>
                  <input type="text" name="code" value="{{$teacher->code}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-user"></i></span>
                  <input type="text" name="fullname" value="{{$teacher->fullname}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-address-card"></i></span>
                  <input type="text" name="cui" value="{{$teacher->cui}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-cake-candles"></i></span>
                  <input type="date" name="birthday" value="{{$teacher->birthday}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-phone"></i></span>
                  <input type="phone" name="phone" value="{{$teacher->phone}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-location-dot"></i></span>
                  <input type="text" name="address" value="{{$teacher->address}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-envelope"></i></span>
                  <input type="email" name="email" value="{{$teacher->email}}" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
              </div>
              <div class="input-group input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fa-solid fa-image"></i></span>
                  <img src="" alt="foto">
              </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                  <button class="btn btn-primary">Editar</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

resources/views/student_homework/index.blade.php
@extends('layouts.app');
@section('content')
<div class="container">
    <div class="row">
        <div class="col text-center shadow-lg p-3 mb-5 bg-body rounded">
            <h3>Calificación</h3>
            <hr>
            <form action="{{route('student_homework.store')}}" method="post" class="form">
                @csrf
                <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg">Estudiante</span>
                  <select name="student_id" id="student_id" class="form-control">
                    <option value="" disabled selected></option>
                    @foreach($students as $student)
                      <option value="{{$student->id}}">{{$student->fullname}}</option>
                    @endforeach
                  </select>
              </div>
              <div class="input-group mb-3 input-group-lg">
                  <span class="input-group-text" id="inputGroup-sizing-lg">Trabajo</span>
                  <select id="homework_id" class="form-control">
                    <option value="" disabled selected></option>
                    @foreach($homeworks as $hm)
                        <option value="{{$hm->id}}_{{$hm->points}}">{{$hm->name}} - {{$hm->matter->name}} - {{$hm->points}}pts.</option>
                    @endforeach
                    <input type="hidden" id="idHomework" name="homework_id">
                  </select>
              </div>
              <div class="input-group mb-3 input-group-lg">
                <span class="input-group-text" id="inputGroup-sizing-lg">Materia</span>
                <select name="level_section_id" id="level_section_id" class="form-control">
                  <option value="" disabled selected></option>
                  @foreach($level_sections as $ls)
                      <option value="{{$ls->id}}">{{$ls->level->number->number}}{{$ls->level->name}}-{{$ls->section->name}}-{{$ls->matter->name}}</option>
                  @endforeach
                </select>
            </div>
            <div class="input-group mb-3 input-group-lg">
                <span class="input-group-text" id="inputGroup-sizing-lg">Puntos</span>
                <input type="text" name="points" id="points" class="form-control">
            </div>
            <br><br><br><br><br>
            <button type="submit" class="btn btn-success">Calificar</button>
            <button class="btn btn-danger">Cancelar</button>
            </form>
        </div>
        <div class="col-md-9 text-center shadow-lg p-3 mb-5 bg-body rounded">
            <h3>Listado de Trabajos Calificados</h3>
            <hr>
            @if(isset($student_homeworks))
                <table class="table table-striped table-hover">
                    <thead class="bg-primary text-white">
                        <tr>
                            <th scope="row">No.</th>
                            <th scope="row">Alumno</th>
                            <th scope="row">Trabajo</th>
                            <th scope="row">Materia</th>
                            <th scope="row">Puntos</th>
                            <th scope="row">Acción</th>
                        </tr>
                    </thead>
                    @foreach($student_homeworks as $sh)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$sh->student->fullname}}</td>
                        <td>{{$sh->homework->name}}</td>
                        <td>{{$sh->level_section->matter->name}}</td>
                        <td>{{$sh->points}}/{{$sh->homework->points}}</td>
                        <td>
                            <a href="" data-bs-toggle="modal" data-bs-target="#editarSH-{{$sh->id}}"><i data-fa-symbol="edit" class="fa-solid fa-pencil fa-fw"></i></a>
                            @if(Auth::user()->type_user->name = 'administrador')
                            <a href="" data-bs-toggle="modal" data-bs-target="#eliminarSH-{{$sh->id}}"><i data-fa-symbol="delete" class="fa-solid fa-trash fa-fw" style="color:red"></i></a>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </table>
                {{ $student_homeworks->links() }}
            @else
                <h3>No Existen Registros!</h3>
                <h5><--- Agrega uno </h5>
            @endif
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $('#points').change(validarPuntos);
        function validarPuntos(){
            homework = document.getElementById('homework_id').value.split('_');
            console.log(homework);
            puntos = homework[1];
            idHomework = homework[0];
            puntosIngresados = $('#points').val();
            if(puntosIngresados<=puntos){
                true;
                $('#idHomework').val(idHomework);
            }else{
                alert('El trabajo tiene un valor de '+puntos);
                $('#points').val(0);
            }
            console.log(puntos);

        }
    </script>
@endpush
@endsection