routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware'=>'auth'],function(){
    Route::resource('typePeople','TypePeopleController');
    Route::resource('typeUser','TypeUserController');
    Route::resource('typeHomework','TypeHomeworkController');
    Route::resource('ciclo','CicloController');
    Route::resource('level','LevelController');
    Route::resource('matter','MatterController');
    Route::resource('section','SectionController');
    Route::resource('student','StudentController');
    Route::resource('teacher','TeacherController');
    Route::resource('people','PeopleController');
    Route::resource('period','PeriodController');
    Route::resource('homework','HomeworkController');
    Route::resource('number','NumberController');
    Route::resource('student_homework','StudentHomeworkController');
    Route::resource('level_section','LevelSectionController');
    Route::resource('student_level','StudentLevelController');
    Route::resource('user','UserController');
    Route::resource('student_people','StudenPeopleController');
    Route::get('descargar-notas/{id}', 'StudentController@print_nota');
    
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/TypeUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TypeUser extends Model
{
    use HasFactory;

    protected $fillable=['name','description'];

    public function level_sections(){
        return $this->hasMany('App\Models\LevelSection');
    }

    public function users(){
        return $this->hasMany('App\Models\User');
    }
}

app/Http/Controllers/TypeUserController.php
<?php

namespace App\Http\Controllers;

use App\Models\TypeUser;
use Illuminate\Http\Request;

class TypeUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tus = TypeUser::orderBy('id','desc')->paginate(5);
        if(isset($tus)){
            return view('type_user.index',compact('tus'));
        }else{
            return view('type_user.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        TypeUser::create($request->all());
        return redirect('typeUser');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\TypeUser  $typeUser
     * @return \Illuminate\Http\Response
     */
    public function show(TypeUser $typeUser)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\TypeUser  $typeUser
     * @return \Illuminate\Http\Response
     */
    public function edit(TypeUser $typeUser)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\TypeUser  $typeUser
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $tu = TypeUser::findOrFail($id);
        $tu->update($request->all());
        return redirect('typeUser');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\TypeUser  $typeUser
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $tu = TypeUser::findOrFail($id);
        $tu->delete();
        return redirect('typeUser');
    }
}

resources/views/type_user/delete.blade.php
<div class="modal fade" id="eliminarTipo-{{$tu->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header btn btn-danger">
          <h5 class="modal-title">Eliminar</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{{route('typeUser.destroy',$tu->id)}}" method="post" class="form">
                <input name="_method" type="hidden" value="DELETE">
                @csrf
                <h4>Confirma que desea eliminar el tipo de usuario. <b>{{$tu->name}}</b></h4>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancelar</button>
                  <button class="btn btn-danger">Eliminar</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

resources/views/type_user/editar.blade.php
<div class="modal fade" id="editarTipo-{{$tu->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header btn btn-primary">
          <h5 class="display-6">Editar</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{{route('typeUser.update',$tu->id)}}" method="post" class="form">
                <input name="_method" type="hidden" value="PATCH">
                @csrf
                <div class="input-group mb-3 input-group-lg">
                    <label for="name" class="input-group-text" id="inputGroup-sizing-lg">Nombre</label>
                    <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="name"  value="{{$tu->name}}" required>
                </div>
                
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                  <button class="btn btn-primary">Editar</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

resources/views/type_user/index.blade.php
@extends('layouts.app');
@section('content')
<div class="container">
    <div class="row">
        <div class="col text-center shadow-lg p-3 mb-5 bg-body rounded">
            <h3>Nuevo Tipo de Usuario</h3>
            <hr>
            <form action="{{route('typeUser.store')}}" method="post" class="form">
                @csrf
                <div class="input-group mb-3 input-group-lg">
                    <span class="input-group-text" id="inputGroup-sizing-lg">Nombre</span>
                    <input type="text" name="name" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" required>
                </div>
                <br><br><br><br><br><br><br><br><br><br><br><br>
                <hr>
                <button type="submit" class="btn btn-success">Guardar</button>
                <button class="btn btn-danger">Cancelar</button>
            </form>
        </div>
        <div class="col-md-9 text-center shadow-lg p-3 mb-5 bg-body rounded">
            <h3>Listado Tipo de Usuario</h3>
            <hr>
            @if(isset($tus))
                <table class="table table-striped table-hover">
                    <thead class="bg-primary text-white">
                        <tr>
                            <th scope="row">No.</th>
                            <th scope="row">Nombre</th>
                            <th scope="row"></th>
                            <th scope="row">Acción</th>
                        </tr>
                    </thead>
                    @foreach($tus as $tu)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$tu->name}}</td>
                        <td>{{$tu->description}}</td>
                        <td>
                            <a href="" data-bs-toggle="modal" data-bs-target="#editarTipo-{{$tu->id}}"><i data-fa-symbol="edit" class="fa-solid fa-pencil fa-fw"></i></a>
                            <a href="" data-bs-toggle="modal" data-bs-target="#eliminarTipo-{{$tu->id}}"><i data-fa-symbol="delete" class="fa-solid fa-trash fa-fw" style="color:red"></i></a>
                        </td>
                    </tr>
                        @include('type_user.editar')
                        @include('type_user.delete')
                    @endforeach
                </table>
                {{ $tus->links() }}
            @else
                <h3>No Existen Registros!</h3>
                <h5><--- Agrega uno </h5>
            @endif
        </div>
    </div>
</div>
@endsection